package Estructuras;

import Analizadores.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;


public class Main extends javax.swing.JFrame {

    Lexico scanner = new Lexico();
    Sintactico automata = new Sintactico();
    Semantico semantico =  new Semantico();
    
    //Para las tablas
    DefaultTableModel ModTabla;
    DefaultTableModel ModTabla2;
    Object[] Result = new Object[3];
    Object[] Result2 = new Object[3];
    
    
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ModTabla = (DefaultTableModel) tbl_Resultados.getModel();
        ModTabla2 = (DefaultTableModel) tbl_Resultados2.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Entrada = new javax.swing.JTextArea();
        bot_ALexico = new javax.swing.JButton();
        bot_ASintactico = new javax.swing.JButton();
        bot_ElegirArcihvo = new javax.swing.JButton();
        bot_Limpiar = new javax.swing.JButton();
        bot_ASemantico = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_Semantico = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_Resultados = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_Resultados2 = new javax.swing.JTable();
        bot_Limpiar1 = new javax.swing.JButton();
        lbl_Lenguaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_Errores = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(255, 0, 255));

        txt_Entrada.setColumns(20);
        txt_Entrada.setRows(5);
        txt_Entrada.setText("Ejemplo.txt");
        txt_Entrada.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_Entrada.setEnabled(false);
        txt_Entrada.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txt_Entrada);

        bot_ALexico.setBackground(new java.awt.Color(102, 255, 255));
        bot_ALexico.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bot_ALexico.setText("Analizador Léxico");
        bot_ALexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_ALexicoActionPerformed(evt);
            }
        });

        bot_ASintactico.setBackground(new java.awt.Color(102, 255, 255));
        bot_ASintactico.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bot_ASintactico.setText("Analizador Sintáctico");
        bot_ASintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_ASintacticoActionPerformed(evt);
            }
        });

        bot_ElegirArcihvo.setBackground(new java.awt.Color(204, 204, 255));
        bot_ElegirArcihvo.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bot_ElegirArcihvo.setText("Añadir Archivo");
        bot_ElegirArcihvo.setAutoscrolls(true);
        bot_ElegirArcihvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_ElegirArcihvoActionPerformed(evt);
            }
        });

        bot_Limpiar.setBackground(new java.awt.Color(204, 204, 255));
        bot_Limpiar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bot_Limpiar.setText("Limpiar");
        bot_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_LimpiarActionPerformed(evt);
            }
        });

        bot_ASemantico.setBackground(new java.awt.Color(102, 255, 255));
        bot_ASemantico.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bot_ASemantico.setText("Analizador Semántico");
        bot_ASemantico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_ASemanticoActionPerformed(evt);
            }
        });

        txt_Semantico.setColumns(20);
        txt_Semantico.setFont(new java.awt.Font("Agency FB", 0, 13)); // NOI18N
        txt_Semantico.setRows(5);
        txt_Semantico.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_Semantico.setEnabled(false);
        jScrollPane4.setViewportView(txt_Semantico);

        tbl_Resultados.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tbl_Resultados.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        tbl_Resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LINEA", "TIPO", "SIMBOLO"
            }
        ));
        jScrollPane5.setViewportView(tbl_Resultados);

        tbl_Resultados2.setBorder(new javax.swing.border.MatteBorder(null));
        tbl_Resultados2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_Resultados2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LINEA", "ENTRADA", "ESTADO"
            }
        ));
        jScrollPane6.setViewportView(tbl_Resultados2);

        bot_Limpiar1.setBackground(new java.awt.Color(204, 255, 153));
        bot_Limpiar1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bot_Limpiar1.setText("Limpiar Tablas");
        bot_Limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_Limpiar1ActionPerformed(evt);
            }
        });

        lbl_Lenguaje.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lbl_Lenguaje.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lbl_Lenguaje.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel1.setText("NÚMERO DE ERRORES:");

        lbl_Errores.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lbl_Errores.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lbl_Errores.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 204));
        jLabel2.setText("RECONOCEDOR DE EXPRESIONES ARITMETICAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/unmsm.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgenes/fisi.png"))); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(255, 255, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Agency FB", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("                GRUPO 12 - LyC\nIntegrantes\n-Alejo Bernuy,Sergio Giovanni\n-Augusto Achic,Brad Kenneth Mijhael\n-Roman Robles,Nicolas Alexander\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(bot_Limpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(bot_ALexico, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(bot_ASintactico))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_Lenguaje)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_Errores, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bot_ASemantico)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bot_ElegirArcihvo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(bot_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bot_ElegirArcihvo)
                            .addComponent(bot_Limpiar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Lenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lbl_Errores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bot_ASintactico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bot_ALexico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bot_ASemantico)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(bot_Limpiar1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_ALexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_ALexicoActionPerformed
        String cadenaCandidata = (String) this.txt_Entrada.getText();
        
        Tokens auxTok = new Tokens();
        int numLineas = 1;
        String texto = "LINEA " + numLineas + "\t\tSIMBOLO\n";
        scanner.setPuntero(0);
        
        do{  
            auxTok = scanner.scanner(cadenaCandidata+'$');  
            
            switch (auxTok.getTipo()) {
                case 0:
                    texto += "<PR>   " + "\t" + auxTok.getSimbolo() + "\n";
                    Result[0] = numLineas;
                    Result[1] = "<PR>";
                    Result[2] = auxTok.getSimbolo();
                    ModTabla.addRow(Result);
                    break;
                case 1:
                    texto += "<ID> \t" + "\t" + auxTok.getSimbolo() + "\n";
                    Result[0] = numLineas;
                    Result[1] = "<ID>";
                    Result[2] = auxTok.getSimbolo();
                    ModTabla.addRow(Result);
                    break;
                case 2:
                    texto += "<OP>   \t" + "\t" + auxTok.getSimbolo() + "\n";
                    Result[0] = numLineas;
                    Result[1] = "<OP>";
                    Result[2] = auxTok.getSimbolo();
                    ModTabla.addRow(Result);
                    break;
                case 3:
                    texto += "<NUM>   \t" + "\t" + auxTok.getSimbolo() + "\n";
                    Result[0] = numLineas;
                    Result[1] = "<NUM>";
                    Result[2] = auxTok.getSimbolo();
                    ModTabla.addRow(Result);
                    break;
                case 4:
                    numLineas++;
                    texto += "\nLINEA " + numLineas + " \n";
                    break;
                default:
                    break;
            }
            
        }while(!auxTok.getSimbolo().equals("Fin de Cadena"));
        
        System.out.print(texto);
        
    }//GEN-LAST:event_bot_ALexicoActionPerformed

    private void bot_ASintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_ASintacticoActionPerformed
        String cadena = (String) this.txt_Entrada.getText();
        
        ArrayList<Integer> aceptada = new ArrayList<>();
        
        String titulo = "LINEA"+"\tENTRADA"+"\tESTADO\n";
        
        String texto = "";
        
        int errores = 0;

        automata.reconocedor(cadena+'$', aceptada);
        
        for (int i = 0; i < aceptada.size(); i++) {

            switch (aceptada.get(i)) {
                //Si se desea visualizar las líneas ignoradas
                /*case 0:
                texto = texto + " " + (i + 1) + " " + "\t" + automata.auxiliar.get(i) + "\tIGNORADA\n";
                break;*/
                case 1:
                    texto = texto + " " + (i + 1) + " " + "\t" + automata.auxiliar.get(i) + "\tACEPTADA\n";
                    Result2[0] = i + 1;
                    Result2[1] = automata.auxiliar.get(i);
                    Result2[2] = "ACEPTADA";
                    ModTabla2.addRow(Result2);
                    break;
                case -1:
                    texto = texto + " " + (i + 1) + " " + "\t" + automata.auxiliar.get(i) + "\tERROR\n";
                    errores++;
                    Result2[0] = i + 1;
                    Result2[1] = automata.auxiliar.get(i);
                    Result2[2] = "NO ACEPTADA";
                    ModTabla2.addRow(Result2);
                    break;
            }
        }
        
        
        if(errores==0){
            System.out.println("");
            System.out.println(titulo + texto + "\nLENGUAJE ACEPTADO, " + errores + " ERRORES");
            //Para la tabla
            String Errores = String.valueOf(errores);
            lbl_Lenguaje.setText("LENGUAJE ACEPTADO");
            lbl_Errores.setText(Errores);
        }else{
            System.out.println(titulo + texto + "\nLENGUAJE NO ACEPTADO, " + errores + " ERRORES");
            //Para la tabla
            String Errores = String.valueOf(errores);
            lbl_Lenguaje.setText("LENGUAJE NO ACEPTADO");
            lbl_Errores.setText(Errores);
        }
        
        //SOLO PARA CORROBORAR EL VALOR DE ACEPTACIÓN DE LA LÍNEA
        int i=0;
        while(i<aceptada.size()){
            System.out.println(aceptada.get(i));
            i++;
        }
       
    }//GEN-LAST:event_bot_ASintacticoActionPerformed

    private void bot_ElegirArcihvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_ElegirArcihvoActionPerformed
        JFileChooser ventanaFichero = new JFileChooser();
        ventanaFichero.showOpenDialog(this);
        File archivo = ventanaFichero.getSelectedFile();

        String cadena;
        try {
            cadena = new String(Files.readAllBytes(archivo.toPath()));
            this.txt_Entrada.setText(cadena);
        } catch (IOException ex) {
        }

        String auxiliar = archivo.getPath();

        try {
            Scanner entrada = new Scanner(new File(auxiliar));

            while (entrada.hasNextLine()) {
                this.automata.crearCadena(entrada.nextLine());
            }

        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_bot_ElegirArcihvoActionPerformed

    private void bot_ASemanticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_ASemanticoActionPerformed
        
        //Guardamos el contenido del text Area
        String expr = (String) this.txt_Entrada.getText();
        
        //Enviamos
        txt_Semantico.setText("Ejecutando:\n"+semantico.analisisSemantico(expr+'$'));
        
    }//GEN-LAST:event_bot_ASemanticoActionPerformed

    private void bot_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_LimpiarActionPerformed
        txt_Entrada.setText("");
    }//GEN-LAST:event_bot_LimpiarActionPerformed

    private void bot_Limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_Limpiar1ActionPerformed
        for (int i = 0; i < ModTabla.getRowCount(); i++) {
            ModTabla.removeRow(i);
            i -= 1;
        }
        
        for (int i = 0; i < ModTabla2.getRowCount(); i++) {
            ModTabla2.removeRow(i);
            i -= 1;
        }
        
        lbl_Errores.setText("");
        lbl_Lenguaje.setText("");
        txt_Semantico.setText("");
    }//GEN-LAST:event_bot_Limpiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_ALexico;
    private javax.swing.JButton bot_ASemantico;
    private javax.swing.JButton bot_ASintactico;
    private javax.swing.JButton bot_ElegirArcihvo;
    private javax.swing.JButton bot_Limpiar;
    private javax.swing.JButton bot_Limpiar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lbl_Errores;
    private javax.swing.JTextField lbl_Lenguaje;
    private javax.swing.JTable tbl_Resultados;
    private javax.swing.JTable tbl_Resultados2;
    private javax.swing.JTextArea txt_Entrada;
    private javax.swing.JTextArea txt_Semantico;
    // End of variables declaration//GEN-END:variables
}
